### ISSUE TITLE
您好  我是一位对Serverless感兴趣的学生 可以和您探讨一下吗？

### ISSUE THREAD

**Issue by zjy5755202** [helloworlde/serverless-spring-boot#2]
我最近学习了Serverless的概念，我在想怎么把传统Spring Boot或者是Spring Cloud微服务迁移到Serverless环境下，但是我感觉单纯的就加一个Handler这样子不做拆分的话那是不是和传统部署在k8s上面是一样的，  因为如果沿用spring的技术的话 ，各个接口实际还是耦合在一个jar包中的，并没有做到serverless粒度的拆分，不知道您在这方面有没有什么想法呢？

**Comment by helloworlde** [comment]
Serverless 适用于功能单一的无状态函数型服务，如给处理图片加水印这样的场景；面对的是类似一个处理方法这样的函数，Spring 这样有状态应用并不适合；如果改造 Spring 服务，即使做到函数化，依然不适用，因为依赖过多，冷启动时间很长

Java 并不是非常适合 Serverless 的场景，Serverless 更适合使用 Node、Python；Spring 在最新的版本中支持使用 GraalVM，启动速度得到大幅提升，可以关注一下

**Comment by zjy5755202** [comment]
谢谢您的解答  
我还想请问下那是不是改造传统单体服务一般就只能改造到微服务的层面 不太能改造到函数化的水平？
还有另外一个问题就是serverless中函数之间的相互调用是怎么实现的，以及serverless环境下会存在分布式事务这样的事务问题吗？

**Comment by helloworlde** [comment]
可以改造，但是没有意义，大部分业务场景不适合 Serverless，不应该为了 Serverless 而 Serverless；
Serverless 函数互相调用有多种方式，如通过发送消息触发、调用HTTP接口触发、通过服务编排等方式；
有分布式事务这样的场景不适合用 Serverless，如果一定要实现，也是可以的
Serverless 可以理解为两个方向，一个是服务函数化，一个是免运维，目前大多数云厂商都支持

**Comment by zjy5755202** [comment]
好的 受教了 谢谢您的解答
